.section .rodata

.global Song_01_30hz_bin
.align 256
Song_01_30hz_bin:
  .incbin "/Users/jasonrowe/Software/Atari7800/Astrowing/src/music/Song_01_30hz.bin"

.global Song_02_30hz_bin
.align 256
Song_02_30hz_bin:
  .incbin "/Users/jasonrowe/Software/Atari7800/Astrowing/src/music/Song_02_30hz.bin"

.global Song_03_30hz_bin
.align 256
Song_03_30hz_bin:
  .incbin "/Users/jasonrowe/Software/Atari7800/Astrowing/src/music/Song_03_30hz.bin"

.global Boss_30hz_bin
.align 256
Boss_30hz_bin:
  .incbin "/Users/jasonrowe/Software/Atari7800/Astrowing/src/music/Boss_30hz.bin"
